[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 20

[[main]]
  name = "Publications"
  pageRef = "publications"
  weight = 30

[[main]]
  name = "Photography"
  pageRef = "photography"
  weight = 40
